# Generated by Django 5.1.1 on 2024-10-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=255)),
                ('percentage_increment', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePayStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inc_aug_15_allowance', models.PositiveIntegerField()),
                ('inc_aug_17_svc_allowance', models.PositiveIntegerField()),
                ('inc_sep_21_svc_allowance', models.PositiveIntegerField()),
                ('mphil_phd_allowance', models.PositiveIntegerField()),
                ('spec_head_hunting_allowance', models.PositiveIntegerField()),
                ('svc_allowance', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('employee_pay_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.paystructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAnnualIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_inc_no', models.PositiveIntegerField()),
                ('date_awarded', models.DateField()),
                ('rate_of_annual_inc', models.CharField(max_length=100)),
                ('total_annual_inc', models.PositiveIntegerField()),
                ('employee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_increments', to='payroll.employeepaystructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pay_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='payroll.employeepaystructure')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='payroll.incrementorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
