# Generated by Django 5.1.1 on 2024-10-18 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_incrementorder_employeepaystructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('days_paid', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('granted_times_in_service', models.PositiveIntegerField()),
                ('granted_times_interval', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_increments', models.FloatField()),
                ('arrears', models.PositiveIntegerField()),
                ('conveyance_allowance', models.PositiveIntegerField()),
                ('cp_fund', models.PositiveIntegerField()),
                ('date_issued', models.DateField()),
                ('education_allowance', models.PositiveIntegerField()),
                ('employee_oldage_benefit_inst', models.PositiveIntegerField()),
                ('eobi', models.PositiveIntegerField()),
                ('house_rent_allowance', models.PositiveIntegerField()),
                ('inc_aug_15_allowance', models.PositiveIntegerField()),
                ('inc_aug_17_svc_allowance', models.PositiveIntegerField()),
                ('inc_sep_21_svc_allowance', models.PositiveIntegerField()),
                ('income_tax', models.PositiveIntegerField()),
                ('increments', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('loan_installment', models.FloatField()),
                ('lowp', models.PositiveIntegerField()),
                ('medical_allowance', models.PositiveIntegerField()),
                ('mphil_phd_allowance', models.PositiveIntegerField()),
                ('pay_roll_no', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=50)),
                ('security_deposit', models.PositiveIntegerField()),
                ('spec_head_huntimg_allowance', models.PositiveIntegerField()),
                ('svc_allowance', models.PositiveIntegerField()),
                ('time_generated', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
                ('employee_pay_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.employeepaystructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deductions', models.PositiveIntegerField()),
                ('executive_approval', models.BooleanField(default=False)),
                ('leave_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('principal_approval', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('secretary_approval', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('vc_approval', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_leaves', to='payroll.leavetype')),
                ('deducted_in_payroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_deducted', to='payroll.payroll')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
