# Generated by Django 5.1.1 on 2024-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_leavetype_payroll_leaves'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeannualincrement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employeepaystructure',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='increment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='incrementorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leaves',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paystructure',
            options={'ordering': ['-created_at']},
        ),
    ]
