# Generated by Django 4.2.16 on 2024-10-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employeeannualincrement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
    ]
