# Generated by Django 4.2.16 on 2024-10-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_merge_20241028_1732'),
        ('payroll', '0006_leaves_employee_payroll_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystructure',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pay Structure', 'verbose_name_plural': 'Pay Structures'},
        ),
        migrations.AlterField(
            model_name='paystructure',
            name='annual_increment',
            field=models.IntegerField(help_text='Enter the annual increment amount.', verbose_name='Annual Increment'),
        ),
        migrations.AlterField(
            model_name='paystructure',
            name='basic_pay',
            field=models.IntegerField(help_text='Enter the basic pay amount.', verbose_name='Basic Pay'),
        ),
        migrations.AlterField(
            model_name='paystructure',
            name='conveyance_allowance',
            field=models.IntegerField(help_text='Enter the conveyance allowance amount.', verbose_name='Conveyance Allowance'),
        ),
        migrations.AlterField(
            model_name='paystructure',
            name='employee_designation',
            field=models.ForeignKey(help_text='Select the designation related to this pay structure.', on_delete=django.db.models.deletion.CASCADE, related_name='pay_structures', to='employee.employeedesignation', verbose_name='Employee Designation'),
        ),
        migrations.AlterField(
            model_name='paystructure',
            name='hra',
            field=models.IntegerField(help_text='Enter the house rent allowance amount.', verbose_name='House Rent Allowance (HRA)'),
        ),
        migrations.AlterField(
            model_name='paystructure',
            name='medical_allowance',
            field=models.IntegerField(help_text='Enter the medical allowance amount.', verbose_name='Medical Allowance'),
        ),
    ]
