# Generated by Django 4.2.16 on 2024-10-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_merge_20241028_1732'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0007_alter_paystructure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeannualincrement',
            options={'ordering': ['-date_awarded'], 'verbose_name': 'Employee Annual Increment', 'verbose_name_plural': 'Employee Annual Increments'},
        ),
        migrations.AlterModelOptions(
            name='employeepaystructure',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee Pay Structure', 'verbose_name_plural': 'Employee Pay Structures'},
        ),
        migrations.AlterModelOptions(
            name='increment',
            options={'ordering': ['-created'], 'verbose_name': 'Employee Increment', 'verbose_name_plural': 'Employee Increments'},
        ),
        migrations.AlterModelOptions(
            name='incrementorder',
            options={'ordering': ['-created'], 'verbose_name': 'Increment Order', 'verbose_name_plural': 'Increment Orders'},
        ),
        migrations.AlterModelOptions(
            name='leaves',
            options={'ordering': ['-request_date'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-date_issued'], 'verbose_name': 'Payroll', 'verbose_name_plural': 'Payrolls'},
        ),
        migrations.AlterField(
            model_name='employeeannualincrement',
            name='annual_inc_no',
            field=models.PositiveIntegerField(verbose_name='Annual Increment Number'),
        ),
        migrations.AlterField(
            model_name='employeeannualincrement',
            name='date_awarded',
            field=models.DateField(verbose_name='Date Awarded'),
        ),
        migrations.AlterField(
            model_name='employeeannualincrement',
            name='employee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_increments', to='payroll.employeepaystructure', verbose_name='Employee Pay Structure'),
        ),
        migrations.AlterField(
            model_name='employeeannualincrement',
            name='rate_of_annual_inc',
            field=models.CharField(max_length=100, verbose_name='Rate of Increment'),
        ),
        migrations.AlterField(
            model_name='employeeannualincrement',
            name='total_annual_inc',
            field=models.PositiveIntegerField(verbose_name='Total Annual Increment'),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_structures', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='employee_pay_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pay_structures', to='payroll.paystructure', verbose_name='Pay Structure'),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='inc_aug_15_allowance',
            field=models.PositiveIntegerField(verbose_name="Inc. Aug '15 Allowance"),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='inc_aug_17_svc_allowance',
            field=models.PositiveIntegerField(verbose_name="Inc. Aug '17 Service Allowance"),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='inc_sep_21_svc_allowance',
            field=models.PositiveIntegerField(verbose_name="Inc. Sep '21 Service Allowance"),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='mphil_phd_allowance',
            field=models.PositiveIntegerField(verbose_name='MPhil/PhD Allowance'),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='spec_head_hunting_allowance',
            field=models.PositiveIntegerField(verbose_name='Special Head-Hunting Allowance'),
        ),
        migrations.AlterField(
            model_name='employeepaystructure',
            name='svc_allowance',
            field=models.PositiveIntegerField(verbose_name='Service Allowance'),
        ),
        migrations.AlterField(
            model_name='increment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Increment Amount'),
        ),
        migrations.AlterField(
            model_name='increment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Increment Date'),
        ),
        migrations.AlterField(
            model_name='increment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='payroll.incrementorder', verbose_name='Related Increment Order'),
        ),
        migrations.AlterField(
            model_name='increment',
            name='pay_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='payroll.employeepaystructure', verbose_name='Employee Pay Structure'),
        ),
        migrations.AlterField(
            model_name='incrementorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Creation Date'),
        ),
        migrations.AlterField(
            model_name='incrementorder',
            name='note',
            field=models.CharField(max_length=255, verbose_name='Order Note'),
        ),
        migrations.AlterField(
            model_name='incrementorder',
            name='percentage_increment',
            field=models.FloatField(verbose_name='Percentage Increment'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='deducted_in_payroll',
            field=models.ForeignKey(help_text='Select the payroll record to which this leave is deducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_deducted', to='payroll.payroll', verbose_name='Deducted in Payroll'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='deductions',
            field=models.PositiveIntegerField(help_text='Enter the amount to be deducted from payroll for this leave.', verbose_name='Payroll Deduction Amount'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='employee',
            field=models.ForeignKey(help_text='Select the employee requesting the leave.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='executive_approval',
            field=models.BooleanField(default=False, help_text='Has the executive approved this leave?', verbose_name='Executive Approval'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_date',
            field=models.DateField(help_text='Select the start date for the leave.', verbose_name='Leave Start Date'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_end_date',
            field=models.DateField(help_text='Select the end date for the leave.', verbose_name='Leave End Date'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_type',
            field=models.ForeignKey(help_text='Select the type of leave.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_leaves', to='payroll.leavetype', verbose_name='Type of Leave'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='note',
            field=models.TextField(blank=True, help_text='Add any additional notes regarding the leave.', verbose_name='Leave Notes'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='principal_approval',
            field=models.BooleanField(default=False, help_text='Has the principal approved this leave?', verbose_name='Principal Approval'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='reason',
            field=models.TextField(help_text='Provide a reason for taking the leave.', verbose_name='Reason for Leave'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='request_date',
            field=models.DateField(auto_now_add=True, help_text='The date when the leave request was made.', verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='secretary_approval',
            field=models.BooleanField(default=False, help_text='Has the secretary approved this leave?', verbose_name='Secretary Approval'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(help_text='Current status of the leave request.', max_length=50, verbose_name='Leave Status'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='vc_approval',
            field=models.BooleanField(default=False, help_text='Has the Vice Chancellor approved this leave?', verbose_name='Vice Chancellor Approval'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_paid',
            field=models.PositiveIntegerField(verbose_name='Paid Days Allowed'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='granted_times_in_service',
            field=models.PositiveIntegerField(verbose_name='Total Times Granted'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='granted_times_interval',
            field=models.PositiveIntegerField(verbose_name='Grant Interval (Months)'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Leave Type Name'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='annual_increments',
            field=models.FloatField(verbose_name='Annual Increments'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='arrears',
            field=models.PositiveIntegerField(verbose_name='Arrears'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='conveyance_allowance',
            field=models.PositiveIntegerField(verbose_name='Conveyance Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cp_fund',
            field=models.PositiveIntegerField(verbose_name='CP Fund'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_issued',
            field=models.DateField(verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='education_allowance',
            field=models.PositiveIntegerField(verbose_name='Education Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee_oldage_benefit_inst',
            field=models.PositiveIntegerField(verbose_name='Old-Age Benefit'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee_pay_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.employeepaystructure', verbose_name='Pay Structure'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='eobi',
            field=models.PositiveIntegerField(verbose_name='EOBI'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='house_rent_allowance',
            field=models.PositiveIntegerField(verbose_name='House Rent Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='inc_aug_15_allowance',
            field=models.PositiveIntegerField(verbose_name="Aug '15 Increment Allowance"),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='inc_aug_17_svc_allowance',
            field=models.PositiveIntegerField(verbose_name="Aug '17 Service Allowance"),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='inc_sep_21_svc_allowance',
            field=models.PositiveIntegerField(verbose_name="Sep '21 Service Allowance"),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='income_tax',
            field=models.PositiveIntegerField(verbose_name='Income Tax'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='increments',
            field=models.FloatField(verbose_name='Increments'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='loan_installment',
            field=models.FloatField(verbose_name='Loan Installment'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='lowp',
            field=models.PositiveIntegerField(verbose_name='Loss of Pay Deduction'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='medical_allowance',
            field=models.PositiveIntegerField(verbose_name='Medical Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='mphil_phd_allowance',
            field=models.PositiveIntegerField(verbose_name='MPhil/PhD Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_roll_no',
            field=models.CharField(max_length=255, verbose_name='Payroll Number'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='security_deposit',
            field=models.PositiveIntegerField(verbose_name='Security Deposit'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='spec_head_huntimg_allowance',
            field=models.PositiveIntegerField(verbose_name='Special Head-Hunting Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='svc_allowance',
            field=models.PositiveIntegerField(verbose_name='Service Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='time_generated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Generated'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AddIndex(
            model_name='employeepaystructure',
            index=models.Index(fields=['employee'], name='payroll_emp_employe_3d53b5_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepaystructure',
            index=models.Index(fields=['employee_pay_structure'], name='payroll_emp_employe_7359ef_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='payroll_pay_employe_3f4ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['date_issued'], name='payroll_pay_date_is_f76dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee_pay_structure'], name='payroll_pay_employe_fdf2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['pay_roll_no'], name='payroll_pay_pay_rol_02e758_idx'),
        ),
        migrations.AddIndex(
            model_name='paystructure',
            index=models.Index(fields=['employee_designation'], name='payroll_pay_employe_e341dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paystructure',
            index=models.Index(fields=['basic_pay'], name='payroll_pay_basic_p_8a1031_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeannualincrement',
            constraint=models.UniqueConstraint(fields=('employee_structure', 'annual_inc_no'), name='unique_increment_per_employee_structure_and_number'),
        ),
        migrations.AddConstraint(
            model_name='employeepaystructure',
            constraint=models.UniqueConstraint(fields=('employee', 'employee_pay_structure'), name='unique_employee_pay_structure'),
        ),
        migrations.AddConstraint(
            model_name='increment',
            constraint=models.UniqueConstraint(fields=('order', 'pay_structure'), name='unique_increment_per_order_and_pay_structure'),
        ),
        migrations.AddConstraint(
            model_name='leaves',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_date'), name='unique_leave_per_employee_and_date'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='unique_leave_type_per_department'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'date_issued'), name='unique_payroll_per_employee_and_date'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('pay_roll_no',), name='unique_payroll_number'),
        ),
        migrations.AddConstraint(
            model_name='paystructure',
            constraint=models.UniqueConstraint(fields=('employee_designation',), name='unique_pay_structure_per_designation'),
        ),
    ]
