# Generated by Django 5.1.1 on 2024-10-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicinfo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='financialinfo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='parentinfo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ['-created_at']},
        ),
    ]
