# Generated by Django 5.1.1 on 2024-10-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_academicinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='father_occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentinfo_father_occupation', to='admission.occupation'),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='guardian_occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentinfo_guardian_occupation', to='admission.occupation'),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentinfo_mother_occupation', to='admission.occupation'),
        ),
    ]
