# Generated by Django 5.1.1 on 2024-10-22 18:46

import app.admission.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_remove_admission_admission_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='other_information',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='admission_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='admission_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='marks_in_previous_school',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='previous_school_roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='extra_act',
            field=models.TextField(blank=True, null=True, verbose_name='Extracurricular Activities'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='sibling',
            field=models.TextField(blank=True, null=True, verbose_name='Sibling Information'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='fee_remaining_for_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fee Remaining for Months (if any)'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='monthly_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='paid_dues_upto_slc',
            field=models.DateField(blank=True, null=True, verbose_name='Paid Dues up to School Leaving Certificate'),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='father_cnic',
            field=models.CharField(max_length=15, validators=[app.admission.models.validate_cnic], verbose_name="Father's CNIC"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='guardian_cnic',
            field=models.CharField(max_length=15, validators=[app.admission.models.validate_cnic], verbose_name="Guardian's CNIC"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='guardian_mobile_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_cnic',
            field=models.CharField(max_length=15, validators=[app.admission.models.validate_cnic], verbose_name="Mother's CNIC"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_mobile_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='disabilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='general_health',
            field=models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='immunization',
            field=models.CharField(choices=[('FULLY_VACCINATED', 'Fully Vaccinated'), ('PARTIALLY_VACCINATED', 'Partially Vaccinated'), ('NOT_VACCINATED', 'Not Vaccinated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mark_of_identification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mobile_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit mobile number.')]),
        ),
    ]
