# Generated by Django 4.2.16 on 2024-11-01 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_category_options_alter_province_options_and_more'),
        ('admission', '0007_alter_academicinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.nationality'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.religion'),
        ),
    ]
