# Generated by Django 4.2.16 on 2024-11-05 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0009_guardianinfo_alter_occupation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
    ]
