# Generated by Django 5.1.1 on 2024-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
