# Generated by Django 5.1.1 on 2024-10-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['-created_at']},
        ),
    ]
