# Generated by Django 4.2.16 on 2024-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_nationality_title_remove_province_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name_plural': 'Nationality'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Provinces'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'verbose_name_plural': 'Religions'},
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
