# Generated by Django 4.2.16 on 2024-11-06 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('bank', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=50)),
                ('covid_vaccinated', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_rejoining', models.DateField(blank=True, null=True)),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_status', models.CharField(max_length=20)),
                ('father_cnic', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('martial_status', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('province', models.CharField(max_length=50)),
                ('wing', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('date_evaluated', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('year_obtained', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academic.department')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedesignation'),
        ),
    ]
