# Generated by Django 5.1.1 on 2024-10-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('bank', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('covid_vaccinated', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_rejoining', models.DateField(blank=True, null=True)),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_status', models.CharField(max_length=50)),
                ('father_cnic', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('martial_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('province', models.CharField(max_length=100)),
                ('wing', models.CharField(max_length=100)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedesignation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_aug_15_allowance', models.PositiveIntegerField()),
                ('inc_aug_17_svc_allowance', models.PositiveIntegerField()),
                ('inc_sep_21_svc_allowance', models.PositiveIntegerField()),
                ('mphil_phd_allowance', models.PositiveIntegerField()),
                ('spec_head_hunting_allowance', models.PositiveIntegerField()),
                ('svc_allowance', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAnnualIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_inc_no', models.PositiveIntegerField()),
                ('date_awarded', models.DateField()),
                ('rate_of_annual_inc', models.CharField(max_length=50)),
                ('total_annual_inc', models.PositiveIntegerField()),
                ('employee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeepaystructure')),
            ],
        ),
        migrations.CreateModel(
            name='PayStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_increment', models.IntegerField()),
                ('basic_pay', models.IntegerField()),
                ('conveyance_allowance', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('employee_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedesignation')),
            ],
        ),
        migrations.AddField(
            model_name='employeepaystructure',
            name='employee_pay_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.paystructure'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_pay_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.paystructure'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year_obtained', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
