# Generated by Django 4.2.16 on 2024-11-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_pay_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.paystructure'),
        ),
    ]
