# Generated by Django 5.1.1 on 2024-10-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_qualification_staffperformance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employeedesignation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='staffperformance',
            options={'ordering': ['-created_at']},
        ),
    ]
