# Generated by Django 4.2.16 on 2024-10-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_staffperformance_options_and_more'),
        ('employee', '0008_qualification'),
    ]

    operations = [
    ]
