# Generated by Django 5.1.1 on 2024-10-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_monthclosing_otherdeposits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cpfund',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cpfunddeposits',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employeearrears',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eobipaid',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='incometaxrates',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='incometaxsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='installmentpaid',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='monthclosing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='otherdeposits',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='securitydeposits',
            options={'ordering': ['-created_at']},
        ),
    ]
