# Generated by Django 4.2.16 on 2024-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_bank_options_alter_cpfund_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpfund',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cpfund',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='cpfunddeposits',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeearrears',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='eobipaid',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eobipaid',
            name='employee',
        ),
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
