# Generated by Django 4.2.16 on 2024-10-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_remove_cpfund_created_by_remove_cpfund_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpfund',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpfund',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpfund', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpfunddeposits',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpfund_deposits_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeearrears',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_arrears', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eobipaid',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eobi_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eobipaid',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eobi_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
