# Generated by Django 4.2.16 on 2024-10-30 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0009_merge_20241028_1732'),
        ('finance', '0007_cpfund_created_by_cpfund_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='cpfund',
            options={'verbose_name': 'CP Fund', 'verbose_name_plural': 'CP Funds'},
        ),
        migrations.AlterModelOptions(
            name='cpfunddeposits',
            options={'verbose_name': 'CP Fund Deposit', 'verbose_name_plural': 'CP Fund Deposits'},
        ),
        migrations.AlterModelOptions(
            name='employeearrears',
            options={'verbose_name': 'Employee Arrears', 'verbose_name_plural': 'Employee Arrears'},
        ),
        migrations.AlterModelOptions(
            name='eobipaid',
            options={'verbose_name': 'EOBI Payment', 'verbose_name_plural': 'EOBI Payments'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='incometaxrates',
            options={'verbose_name': 'Income Tax Rate', 'verbose_name_plural': 'Income Tax Rates'},
        ),
        migrations.AlterModelOptions(
            name='incometaxsession',
            options={'verbose_name': 'Income Tax Session', 'verbose_name_plural': 'Income Tax Sessions'},
        ),
        migrations.AlterModelOptions(
            name='installmentpaid',
            options={'verbose_name': 'Installment Paid', 'verbose_name_plural': 'Installments Paid'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AlterModelOptions(
            name='monthclosing',
            options={'verbose_name': 'Month Closing', 'verbose_name_plural': 'Month Closings'},
        ),
        migrations.AlterModelOptions(
            name='otherdeposits',
            options={'verbose_name': 'Other Deposit', 'verbose_name_plural': 'Other Deposits'},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name': 'Security', 'verbose_name_plural': 'Securities'},
        ),
        migrations.AlterModelOptions(
            name='securitydeposits',
            options={'verbose_name': 'Security Deposit', 'verbose_name_plural': 'Security Deposits'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_account_no',
            field=models.CharField(help_text='Unique account number for the bank.', max_length=255, unique=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_address',
            field=models.CharField(help_text='Physical address of the bank.', max_length=255, verbose_name='Bank Address'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(help_text='The unique code assigned to the bank.', max_length=255, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_contact',
            field=models.CharField(help_text='Contact number for the bank.', max_length=20, verbose_name='Bank Contact Number'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_for_security',
            field=models.BooleanField(default=False, help_text='Indicates if the bank is for security purposes.', verbose_name='Security Flag'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_manager',
            field=models.CharField(help_text='Name of the bank manager.', max_length=255, verbose_name='Bank Manager'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(help_text='Name of the bank.', max_length=255, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='show_on_voucher',
            field=models.BooleanField(default=False, help_text='Indicates if the bank details should be shown on vouchers.', verbose_name='Show on Voucher'),
        ),
        migrations.AlterField(
            model_name='cpfund',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this CP Fund.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='cpfund',
            name='deposited_cp_fund',
            field=models.PositiveIntegerField(help_text='Amount deposited into the CP Fund.', verbose_name='Deposited CP Fund'),
        ),
        migrations.AlterField(
            model_name='cpfund',
            name='employee',
            field=models.OneToOneField(help_text='The employee associated with this CP Fund.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpfund', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='cpfunddeposits',
            name='amount',
            field=models.PositiveIntegerField(help_text='The amount deposited to the CP fund.', verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cpfunddeposits',
            name='cp_fund',
            field=models.ForeignKey(help_text='The CP Fund to which the deposit is made.', on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='finance.cpfund', verbose_name='CP Fund'),
        ),
        migrations.AlterField(
            model_name='cpfunddeposits',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this deposit entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpfund_deposits_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='cpfunddeposits',
            name='note',
            field=models.CharField(help_text='Any additional notes regarding the deposit.', max_length=255, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='employeearrears',
            name='arrears_amount',
            field=models.IntegerField(help_text='Total amount of arrears for the employee.', verbose_name='Arrears Amount'),
        ),
        migrations.AlterField(
            model_name='employeearrears',
            name='arrears_note',
            field=models.CharField(help_text='Notes regarding the arrears.', max_length=255, verbose_name='Arrears Note'),
        ),
        migrations.AlterField(
            model_name='employeearrears',
            name='employee',
            field=models.OneToOneField(help_text='The employee associated with these arrears.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_arrears', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='eobipaid',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this EOBI payment entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eobi_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='eobipaid',
            name='employee',
            field=models.ForeignKey(help_text='The employee for whom the EOBI payment is made.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eobi_employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='eobipaid',
            name='total_deposit',
            field=models.FloatField(help_text='Total amount deposited for EOBI.', verbose_name='Total Deposit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of the expense.', max_digits=10, verbose_name='Expense Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(help_text='Detailed description of the expense.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(help_text='Title of the expense.', max_length=255, verbose_name='Expense Title'),
        ),
        migrations.AlterField(
            model_name='incometaxrates',
            name='initial_taxable_income',
            field=models.PositiveIntegerField(help_text='The starting amount of taxable income.', verbose_name='Initial Taxable Income'),
        ),
        migrations.AlterField(
            model_name='incometaxrates',
            name='percentage',
            field=models.FloatField(help_text='The percentage of tax applied within this income bracket.', verbose_name='Tax Percentage'),
        ),
        migrations.AlterField(
            model_name='incometaxrates',
            name='session',
            field=models.ForeignKey(help_text='Tax session to which this rate applies.', on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_rates', to='finance.incometaxsession', verbose_name='Tax Session'),
        ),
        migrations.AlterField(
            model_name='incometaxsession',
            name='end_date',
            field=models.DateField(help_text='End date of the income tax session.', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='incometaxsession',
            name='start_date',
            field=models.DateField(help_text='Start date of the income tax session.', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='installmentpaid',
            name='amount_paid',
            field=models.FloatField(help_text='The amount paid in this installment.', verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='installmentpaid',
            name='loan',
            field=models.ForeignKey(help_text='Loan associated with this installment payment.', on_delete=django.db.models.deletion.CASCADE, related_name='installments_paid', to='finance.loan', verbose_name='Loan'),
        ),
        migrations.AlterField(
            model_name='installmentpaid',
            name='session',
            field=models.ForeignKey(help_text='Tax session related to this installment.', on_delete=django.db.models.deletion.CASCADE, related_name='installments_paid', to='finance.incometaxsession', verbose_name='Tax Session'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this loan entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(help_text='Total amount of the loan.', verbose_name='Loan Amount'),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Closing amount for the month.', max_digits=10, verbose_name='Closing Amount'),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='closing_month',
            field=models.ForeignKey(help_text='Month for which this closing is applicable.', on_delete=django.db.models.deletion.CASCADE, related_name='month_closings', to='finance.incometaxsession', verbose_name='Closing Month'),
        ),
        migrations.AlterField(
            model_name='otherdeposits',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of the other deposit.', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='otherdeposits',
            name='note',
            field=models.TextField(help_text='Notes regarding the deposit.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='security',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this security entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='security',
            name='note',
            field=models.TextField(help_text='Notes regarding the security.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='securitydeposits',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of the security deposit.', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='securitydeposits',
            name='security',
            field=models.ForeignKey(help_text='Security associated with this deposit.', on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='finance.security', verbose_name='Security'),
        ),
    ]
