# Generated by Django 4.2.16 on 2024-11-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_bank_options_alter_cpfund_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incometaxsession',
            name='starting_year_before_ending_year',
        ),
    ]
