# Generated by Django 5.1.1 on 2024-10-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaserecord_item_returntovendor_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
            preserve_default=False,
        ),
    ]
