# Generated by Django 5.1.1 on 2024-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_issuance_returnfromdepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='itemsinstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaserecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnfromdepartment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returntovendor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at']},
        ),
    ]
