# Generated by Django 4.2.16 on 2024-10-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_class_options_alter_department_options_and_more'),
        ('common', '0005_alter_category_options_alter_province_options_and_more'),
        ('inventory', '0003_alter_issuance_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuance',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemsinstock',
            options={'ordering': ['item__name']},
        ),
        migrations.AlterModelOptions(
            name='purchaserecord',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AlterModelOptions(
            name='returnfromdepartment',
            options={'ordering': ['-return_date']},
        ),
        migrations.AlterModelOptions(
            name='returntovendor',
            options={'ordering': ['-return_date']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='returnfromdepartment',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='academic.department'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='inventory.itemsinstock'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='itemsinstock',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.itemsinstock'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='returnfromdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='academic.department'),
        ),
        migrations.AlterField(
            model_name='returnfromdepartment',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns_from_department', to='inventory.itemsinstock'),
        ),
        migrations.AlterField(
            model_name='returntovendor',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='returntovendor',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.itemsinstock'),
        ),
        migrations.AlterField(
            model_name='returntovendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaserecord',
            unique_together={('invoice_number', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'category'], name='inventory_i_name_f4f10e_idx'),
        ),
    ]
