# Generated by Django 5.1.1 on 2024-10-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('common', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_status', models.CharField(max_length=64)),
                ('admission_type', models.CharField(max_length=64)),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('development_fund', models.PositiveIntegerField(default=0)),
                ('misc', models.PositiveIntegerField(default=0)),
                ('admission', models.PositiveIntegerField(default=0)),
                ('security', models.PositiveIntegerField(default=0)),
                ('building', models.PositiveIntegerField(default=0)),
                ('id_card_fee', models.PositiveIntegerField(default=0)),
                ('examination', models.PositiveIntegerField(default=0)),
                ('fine', models.PositiveIntegerField(default=0)),
                ('prospectus', models.PositiveIntegerField(default=0)),
                ('trip', models.PositiveIntegerField(default=0)),
                ('others_note', models.CharField(blank=True, max_length=64, null=True)),
                ('others', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category')),
                ('class_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Class')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
