# Generated by Django 4.2.16 on 2024-11-06 19:13

import app.fee.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('finance', '0001_initial'),
        ('student', '0001_initial'),
        ('admission', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_status', models.CharField(max_length=64)),
                ('admission_type', models.CharField(max_length=64)),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('development_fund', models.PositiveIntegerField(default=0)),
                ('misc', models.PositiveIntegerField(default=0)),
                ('admission', models.PositiveIntegerField(default=0)),
                ('security', models.PositiveIntegerField(default=0)),
                ('building', models.PositiveIntegerField(default=0)),
                ('id_card_fee', models.PositiveIntegerField(default=0)),
                ('examination', models.PositiveIntegerField(default=0)),
                ('fine', models.PositiveIntegerField(default=0)),
                ('prospectus', models.PositiveIntegerField(default=0)),
                ('trip', models.PositiveIntegerField(default=0)),
                ('others_note', models.CharField(blank=True, max_length=64, null=True)),
                ('others', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category')),
                ('class_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Class')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherGenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('apply_arrears', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('extra_charges', models.PositiveIntegerField()),
                ('extra_charges_note', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('late_payment_fine', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(max_length=12)),
                ('class_section', models.CharField(blank=True, max_length=12, null=True)),
                ('time_generated', models.DateTimeField(auto_now_add=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('dev_fund', models.PositiveIntegerField(default=0)),
                ('misc_fee', models.PositiveIntegerField(default=0)),
                ('admission_fee', models.PositiveIntegerField(default=0)),
                ('security_fee', models.PositiveIntegerField(default=0)),
                ('prospectus_fee', models.PositiveIntegerField(default=0)),
                ('arrears', models.PositiveIntegerField(default=0)),
                ('advance', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(default=app.fee.models.get_due_date)),
                ('late_payment_fine', models.PositiveIntegerField(default=300)),
                ('extra_charges', models.PositiveIntegerField(default=0)),
                ('extra_charges_note', models.CharField(blank=True, max_length=64, null=True)),
                ('total_fee', models.IntegerField(blank=True, null=True)),
                ('total_fee_after_due_date', models.IntegerField(blank=True, null=True)),
                ('arrears_tuition_fee', models.PositiveIntegerField(default=0)),
                ('arrears_development_fund', models.PositiveIntegerField(default=0)),
                ('arrears_misc', models.PositiveIntegerField(default=0)),
                ('arrears_fine', models.PositiveIntegerField(default=0)),
                ('arrears_others', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('partial_paid', models.BooleanField(default=False)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('is_security_voucher', models.BooleanField(default=False)),
                ('is_admission_voucher', models.BooleanField(default=False)),
                ('is_extras_voucher', models.BooleanField(default=False)),
                ('voucher_type', models.CharField(max_length=64)),
                ('is_advance_voucher', models.BooleanField(default=False)),
                ('total_months_advance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('advance_start_month', models.DateField(blank=True, null=True)),
                ('advance_end_month', models.DateField(blank=True, null=True)),
                ('form_b_no', models.CharField(blank=True, max_length=15, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admission.admission')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fee.feestructure')),
                ('previous_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.studentfeevoucher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('date_submitted', models.DateField()),
                ('paid_full', models.BooleanField()),
                ('paid_full_after_due_date', models.BooleanField()),
                ('paid_full_after_due_date_waive_fine', models.BooleanField()),
                ('paid_full_after_due_date_without_fine', models.BooleanField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.studentfeevoucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('date_submitted', models.DateField()),
                ('is_refunded', models.BooleanField()),
                ('paid_to', models.CharField(max_length=255)),
                ('refund_date', models.DateField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('student_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
