# Generated by Django 5.1.1 on 2024-10-18 09:02

import app.fee.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
        ('fee', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(max_length=12)),
                ('class_section', models.CharField(blank=True, max_length=12, null=True)),
                ('time_generated', models.DateTimeField(auto_now_add=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('dev_fund', models.PositiveIntegerField(default=0)),
                ('misc_fee', models.PositiveIntegerField(default=0)),
                ('admission_fee', models.PositiveIntegerField(default=0)),
                ('security_fee', models.PositiveIntegerField(default=0)),
                ('prospectus_fee', models.PositiveIntegerField(default=0)),
                ('arrears', models.PositiveIntegerField(default=0)),
                ('advance', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(default=app.fee.models.get_due_date)),
                ('late_payment_fine', models.PositiveIntegerField(default=300)),
                ('extra_charges', models.PositiveIntegerField(default=0)),
                ('extra_charges_note', models.CharField(blank=True, max_length=64, null=True)),
                ('total_fee', models.IntegerField(blank=True, null=True)),
                ('total_fee_after_due_date', models.IntegerField(blank=True, null=True)),
                ('arrears_tuition_fee', models.PositiveIntegerField(default=0)),
                ('arrears_development_fund', models.PositiveIntegerField(default=0)),
                ('arrears_misc', models.PositiveIntegerField(default=0)),
                ('arrears_fine', models.PositiveIntegerField(default=0)),
                ('arrears_others', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('partial_paid', models.BooleanField(default=False)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('is_security_voucher', models.BooleanField(default=False)),
                ('is_admission_voucher', models.BooleanField(default=False)),
                ('is_extras_voucher', models.BooleanField(default=False)),
                ('voucher_type', models.CharField(max_length=64)),
                ('is_advance_voucher', models.BooleanField(default=False)),
                ('total_months_advance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('advance_start_month', models.DateField(blank=True, null=True)),
                ('advance_end_month', models.DateField(blank=True, null=True)),
                ('form_b_no', models.CharField(blank=True, max_length=15, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admission.admission')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fee.feestructure')),
                ('previous_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.studentfeevoucher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
