# Generated by Django 5.1.1 on 2024-10-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_studentfeevoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherGenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('apply_arrears', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('extra_charges', models.PositiveIntegerField()),
                ('extra_charges_note', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('late_payment_fine', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
