# Generated by Django 5.1.1 on 2024-10-18 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_vouchergenerationrule'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('date_submitted', models.DateField()),
                ('paid_full', models.BooleanField()),
                ('paid_full_after_due_date', models.BooleanField()),
                ('paid_full_after_due_date_waive_fine', models.BooleanField()),
                ('paid_full_after_due_date_without_fine', models.BooleanField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.studentfeevoucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
