# Generated by Django 5.1.1 on 2024-10-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_studentfee'),
        ('finance', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('date_submitted', models.DateField()),
                ('is_refunded', models.BooleanField()),
                ('paid_to', models.CharField(max_length=255)),
                ('refund_date', models.DateField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('student_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.studentfee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
