# Generated by Django 5.1.1 on 2024-10-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0005_securityfee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='securityfee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vouchergenerationrule',
            options={'ordering': ['-created_at']},
        ),
    ]
