# Generated by Django 4.2.16 on 2024-10-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0006_alter_feestructure_options_alter_securityfee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='created_by',
        ),
    ]
