# Generated by Django 4.2.16 on 2024-11-10 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_no', models.CharField(editable=False, help_text='Auto-generated semantic roll number.', max_length=50, null=True, unique=True, verbose_name='Roll Number')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates whether the student has been verified.', null=True, verbose_name='Verification Status')),
                ('student_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='enrolled', help_text='Current status of the student.', max_length=20, null=True, verbose_name='Student Status')),
                ('note', models.TextField(blank=True, help_text='Any additional notes regarding the student.', null=True, verbose_name='Additional Notes')),
                ('admission', models.OneToOneField(help_text='The related admission record.', null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission', verbose_name='Admission Record')),
                ('user', models.ForeignKey(blank=True, help_text='The user account associated with this student (parent/guardian).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'indexes': [models.Index(fields=['roll_no'], name='roll_no_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_no',), name='unique_roll_no'),
        ),
    ]
