# Generated by Django 5.1.1 on 2024-10-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_no', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('admission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
