# Generated by Django 4.2.16 on 2024-10-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_remove_additionalinfo_other_information_and_more'),
        ('student', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.OneToOneField(help_text='The admission record associated with this student.', null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission', verbose_name='Admission Record'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the student has been verified.', verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, help_text='Any additional notes regarding the student.', null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(help_text='Unique roll number assigned to the student.', max_length=50, unique=True, verbose_name='Roll Number'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_no'], name='roll_no_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_no',), name='unique_roll_no'),
        ),
    ]
