# Generated by Django 4.2.16 on 2024-11-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_alter_additionalinfo_nationality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_alter_student_options_alter_student_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The user account associated with this student (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.OneToOneField(help_text='The related admission record.', null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission', verbose_name='Admission Record'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the student has been verified.', null=True, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(help_text='Unique roll number assigned to the student.', max_length=50, null=True, unique=True, verbose_name='Roll Number'),
        ),
    ]
