# Generated by Django 4.2.16 on 2024-11-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_student_user_alter_student_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='enrolled', help_text='Current status of the student.', max_length=20, null=True, verbose_name='Student Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(editable=False, help_text='Auto-generated semantic roll number.', max_length=50, null=True, unique=True, verbose_name='Roll Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user account associated with this student (parent/guardian).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account'),
        ),
    ]
