# Generated by Django 4.2.16 on 2024-11-10 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('label', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, null=True)),
                ('schedule', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_enrolled', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=264, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('section_of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLeavingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_date', models.DateField(db_index=True)),
                ('leaving_date', models.DateField(blank=True, db_index=True, null=True)),
                ('arrears_remaining', models.PositiveIntegerField(default=0)),
                ('is_refunded', models.BooleanField(db_index=True)),
                ('security_refunded', models.PositiveIntegerField(default=0)),
                ('paid_to', models.CharField(db_index=True, max_length=255)),
                ('received_by', models.CharField(db_index=True, max_length=255)),
                ('refund_date', models.DateField(blank=True, db_index=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('admission_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slc_admission_class', to='academic.class')),
                ('last_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slc_last_class', to='academic.class')),
            ],
        ),
    ]
