# Generated by Django 4.2.16 on 2024-11-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolleavingcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='academic_de_name_67e679_idx'),
        ),
        migrations.AddField(
            model_name='course',
            name='class_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='academic_cl_name_5b3621_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['label'], name='academic_cl_label_89bccc_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_class', 'subject_type'], name='academic_su_subject_5748d9_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_of_class', 'name'], name='academic_se_section_9a9640_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolleavingcertificate',
            index=models.Index(fields=['student', 'admission_class'], name='academic_sc_student_85ff86_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolleavingcertificate',
            index=models.Index(fields=['admission_date', 'is_refunded'], name='academic_sc_admissi_920476_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolleavingcertificate',
            index=models.Index(fields=['paid_to', 'received_by'], name='academic_sc_paid_to_c6ddd5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course', 'date_enrolled'], name='academic_en_student_b9f76d_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'class_enrolled', 'subject'), name='unique_course'),
        ),
    ]
