# Generated by Django 5.1.1 on 2024-10-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_department'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLeavingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_date', models.DateField()),
                ('arrears_remaining', models.PositiveIntegerField()),
                ('is_refunded', models.BooleanField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('paid_to', models.CharField(max_length=255)),
                ('received_by', models.CharField(max_length=255)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('security_refunded', models.PositiveIntegerField()),
                ('admission_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slc_admission_class', to='academic.class')),
                ('last_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slc_last_class', to='academic.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
