# Generated by Django 5.1.1 on 2024-10-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_schoolleavingcertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
