# Generated by Django 5.1.1 on 2024-10-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='schoolleavingcertificate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['-created_at']},
        ),
    ]
