# Generated by Django 4.2.16 on 2024-10-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_class_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
        migrations.RemoveField(
            model_name='class',
            name='label',
        ),
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
    ]
