# Generated by Django 4.2.16 on 2024-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_remove_class_description_remove_class_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='label',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='academic_cl_name_5b3621_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['label'], name='academic_cl_label_89bccc_idx'),
        ),
    ]
