# Generated by Django 4.2.16 on 2024-10-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_class_options_class_description_class_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
    ]
