# Generated by Django 4.2.16 on 2024-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='academic_de_name_67e679_idx'),
        ),
    ]
