# Generated by Django 4.2.16 on 2024-10-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_department_options_department_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolleavingcertificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={},
        ),
        migrations.AlterField(
            model_name='schoolleavingcertificate',
            name='admission_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='schoolleavingcertificate',
            name='arrears_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolleavingcertificate',
            name='is_refunded',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='schoolleavingcertificate',
            name='paid_to',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolleavingcertificate',
            name='received_by',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolleavingcertificate',
            name='security_refunded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='schoolleavingcertificate',
            index=models.Index(fields=['student', 'admission_class'], name='academic_sc_student_85ff86_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolleavingcertificate',
            index=models.Index(fields=['admission_date', 'is_refunded'], name='academic_sc_admissi_920476_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolleavingcertificate',
            index=models.Index(fields=['paid_to', 'received_by'], name='academic_sc_paid_to_c6ddd5_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_of_class', 'name'], name='academic_se_section_9a9640_idx'),
        ),
        migrations.AddIndex(
            model_name='subjects',
            index=models.Index(fields=['subject_class', 'subject_type'], name='academic_su_subject_9150ed_idx'),
        ),
    ]
