# Generated by Django 4.2.16 on 2024-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_schoolleavingcertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolleavingcertificate',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='uuid',
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True, unique=True),
        ),
    ]
