# Generated by Django 4.2.16 on 2024-11-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_course_enrollment'),
        ('academic', '0014_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
    ]
