# Generated by Django 4.2.16 on 2024-11-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_role_profile_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default='pending', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role'),
        ),
    ]
